version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=pingpong
      - POSTGRES_PASSWORD=pingpong
      - POSTGRES_DB=pingpong
  back:
    build: ./back
    volumes:
      - ./back:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
